# code generated by ipythons %save command
# first you should run `ipython -i train_age.py`

# coding: utf-8
import phantom
import numpy as np
import cv2
import onnxruntime as rt
get_ipython().run_line_magic('cd', 'gender/')
sess = rt.InferenceSession("age_model.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
img = cv2.imread("c:/test/IMG-20151129-WA0002.jpg")
pred_onx = sess.run([label_name], {input_name: np.array(faces, dtype=np.float32)})
faces = phantom.faces.encode(img)
pred_onx = sess.run([label_name], {input_name: np.array(faces, dtype=np.float32)})
pred_onx
[phantom.faces.estimate_age(f) for f in faces]
get_ipython().run_line_magic('save', 'onnx_session 1-13')
